foodmania_website/urls.py
from django.urls import path
from foodmania_website.views import HomePageView, OrderListView, OrderDetailView, \
    CheckoutView, AddToCartView, CartView, IncreaseItemQuantityView, DecreaseItemQuantityView, \
    RemoveItemFromCartView, AdminDashboardView, order_payment, callback, OrderDeliveredStatusView, \
    OrderRefundedStatusView, NewsLetterView

app_name = 'foodmania_website'

urlpatterns = [


    path('', HomePageView.as_view(), name='website'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),

    path('add-to-cart/<int:pk>/', AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('increase-quantity/<int:pk>/', IncreaseItemQuantityView.as_view(), name='increase_quantity'),
    path('decrease-quantity/<int:pk>/', DecreaseItemQuantityView.as_view(), name='decrease_quantity'),
    path('remove-from-cart/<int:pk>/', RemoveItemFromCartView.as_view(), name='remove_from_cart'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/', order_payment, name='payment'),
    path('callback/', callback, name='callback'),
    path('order/list/', OrderListView.as_view(), name='order_list'),
    path('order/status/delivered/<int:pk>/', OrderDeliveredStatusView.as_view(), name='delivered_status'),
    path('order/status/refunded/<int:pk>/', OrderRefundedStatusView.as_view(), name='refunded_status'),
    path('order/detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('newsletter/', NewsLetterView.as_view(), name='newsletter')


]

rms/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path, include

urlpatterns = [


    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('foodmania.urls')),
    path('', include('user.urls')),
    path('', include('foodmania_website.urls')),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

templates/frontend/payment/callback.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0,
          minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Foodmania</title>
    <link rel="icon" type="image/x-icon" href="/media/foodmania.png">

    <!--bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet" crossorigin="anonymous"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--font awesome icons-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <link href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css" rel="stylesheet">
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <!--for bootstrap select2-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet">

    <!--Chart js-->
    <script crossorigin="anonymous"
            integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw="
            src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css"
          integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" rel="stylesheet"/>

    <!--Sweet Alert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!--Datatable-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css"
          rel="stylesheet">
    <link href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>

    <!--for custom css files-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/callback.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/user_address.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/navbar.css' %}"/>
</head>
<body style="background: rgba(11, 122, 114, 0.2)">
<header>
<!--Navbar-->
<nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background: rgba(108, 117, 125, 0.6)">
    <div class="container-fluid">
        {% if user.is_superuser or user.is_staff %}
        <a class="navbar-brand" href="{% url 'foodmania_website:dashboard' %}"
           style="color: rgba(11, 122, 114, 1)"><b>ADMIN MANAGEMENT</b></a>
        {% else %}
        <a class="navbar-brand" href="{% url 'foodmania_website:website' %}"
           style="color: rgba(11, 122, 114, 1)"><b>FOODMANIA</b></a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>
<!-- End Navbar -->
</header>
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">
        {% if status == "Success" %}
        <div class="card mb-5">
            <div class="card-body p-4">
                <div style="margin: auto">
                    <p class="mb-0 me-5">
                <span>
                    <div class="box">
                        <div class="success alert">
                            <div class="alert-body">
                                Success !
                            </div>
                        </div>
                    </div>
                    </span>
                    </p>
                </div>
            </div>
        </div>
        <div class="card mb-5">
            <div class="card-body p-4">
                <div style="margin: auto">
                    <p class="mb-0 me-5">
                <span>
                    <strong class="text-success" style="font-size: 15px;font-weight: bold;margin: auto">
                        YOUR PAYMENT HAS BEEN SUCCESSFUL AND ORDER IS CONFIRMED. YOU CAN VIEW ORDER DETAILS.
                    </strong>
                    <a class="btn btn-primary" href="{% url 'foodmania_website:order_detail' order_id %}">
                        Order Details
                    </a>
                </span>
                    </p>
                </div>
            </div>
        </div>
        {% elif status == "Pending" or status == "Failure" %}
        <div class="card mb-5">
            <div class="card-body p-4">
                <div style="margin: auto">
                    <p class="mb-0 me-5">
                <span>
                    <div class="box">
                        <div class="error alert">
                            <div class="alert-body">
                                Failure !
                            </div>
                        </div>
                    </div>
                    </span>
                    </p>
                </div>
            </div>
        </div>
        <div class="card mb-5">
            <div class="card-body p-4">
                <div style="margin: auto">
                    <p class="mb-0 me-5">
                <span>
                    <strong class="text-danger" style="font-size: 15px;font-weight: bold;margin: auto">
                        YOUR PAYMENT HAS BEEN DECLINED AND ORDER IS CANCELED.
                    </strong>
                    <a class="btn btn-primary" href="{% url 'foodmania_website:website' %}">
                        Home
                    </a>
                </span>
                    </p>
                </div>
            </div>
        </div>
        {% else %}
        <div class="card mb-5">
            <div class="card-body p-4">
                <div style="margin: auto">
                    <p class="mb-0 me-5">
                <span>
                    <div class="box">
                        <div class="error alert">
                            <div class="alert-body">
                                Error !
                            </div>
                        </div>
                    </div>
                    </span>
                    </p>
                </div>
            </div>
        </div>
        <div class="card mb-5">
            <div class="card-body p-4">
                <div style="margin: auto">
                    <p class="mb-0 me-5">
                <span>
                    <strong class="text-secondary" style="font-size: 15px;font-weight: bold;margin: auto">
                        YOU DON'T HAVE PERMISSION TO VIEW THIS PAGE. PLEASE GO BACK TO
                    </strong>
                    <a class="btn btn-primary" href="{% url 'foodmania_website:website' %}"
                       style="margin-right: 10px;">Home</a>
                </span>
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</main>
<footer>
    {% include 'footer.html' %}
</footer>
</body>
</html>

templates/frontend/payment/payment.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
    var options = {
        key: "{{ razorpay_key }}",
        amount: "{{ order.order.order_total }}",
        currency: "INR",
        name: "{{ order.user.first_name }} {{ order.user.last_name }}",
        description: "Test Transaction",
        image: "/media/foodmania.png",
        order_id: "{{ order.provider_order_id }}",
        callback_url: "{{ callback_url }}",
        redirect: true,
        prefill: {
            "name": "{{ order.user.first_name }} {{ order.user.last_name }}",
            "email": "{{ order.user.email }}",
            "contact": "{{ order.user.phone_number }}"
        },
        notes: {
            "address": "{{ order.order.delivery_address }}"
        },
        theme: {
            "color": "#0b7a72"
        }
    };
    var rzp1 = new Razorpay(options);
    rzp1.open();
    </script>
</form>
{% endblock content %}