foodmania/urls.py
from django.urls import path
from foodmania.views import CategoryCreateView, CategoryListView, CategoryUpdateView, \
    CategoryDeleteView, FoodCreateView, FoodListView, FoodUpdateView, FoodDeleteView

app_name = 'foodmania'

urlpatterns = [


    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('food/create/', FoodCreateView.as_view(), name='food_create'),
    path('food/list/', FoodListView.as_view(), name='food_list'),
    path('food/update/<str:pk>/', FoodUpdateView.as_view(), name='food_update'),
    path('food/delete/<str:pk>/', FoodDeleteView.as_view(), name='food_delete')


]

foodmania_website/urls.py
from django.urls import path
from foodmania_website.views import HomePageView, OrderListView, OrderDetailView, \
    CheckoutView, AddToCartView, CartView, IncreaseItemQuantityView, DecreaseItemQuantityView, \
    RemoveItemFromCartView, AdminDashboardView, order_payment, callback, OrderDeliveredStatusView, \
    OrderRefundedStatusView, NewsLetterView

app_name = 'foodmania_website'

urlpatterns = [


    path('', HomePageView.as_view(), name='website'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),

    path('add-to-cart/<int:pk>/', AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('increase-quantity/<int:pk>/', IncreaseItemQuantityView.as_view(), name='increase_quantity'),
    path('decrease-quantity/<int:pk>/', DecreaseItemQuantityView.as_view(), name='decrease_quantity'),
    path('remove-from-cart/<int:pk>/', RemoveItemFromCartView.as_view(), name='remove_from_cart'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/', order_payment, name='payment'),
    path('callback/', callback, name='callback'),
    path('order/list/', OrderListView.as_view(), name='order_list'),
    path('order/status/delivered/<int:pk>/', OrderDeliveredStatusView.as_view(), name='delivered_status'),
    path('order/status/refunded/<int:pk>/', OrderRefundedStatusView.as_view(), name='refunded_status'),
    path('order/detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('newsletter/', NewsLetterView.as_view(), name='newsletter')


]

rms/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path, include

urlpatterns = [


    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('foodmania.urls')),
    path('', include('user.urls')),
    path('', include('foodmania_website.urls')),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

user/urls.py
"""This file contains site deployment data such as server names and ports."""

from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView, \
    PasswordResetConfirmView, PasswordChangeView
from django.conf.urls.static import static
from user.views import SignupView, ProfileView, UserDeleteView, UserListView,\
    UserAddressCreateView, UserAddressListView, UserAddressUpdateView, UserAddressDeleteView
from user.forms import LoginForm
from rms import settings

app_name = 'user'

urlpatterns = [


    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name="registration/login.html",
                                     form_class=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/change/', PasswordChangeView.as_view(), name='password_change'),
    # path('password/change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('user/list/', UserListView.as_view(), name='user_list'),

    path('address/create/', UserAddressCreateView.as_view(), name='address_create'),
    path('address/list/', UserAddressListView.as_view(), name='address_list'),
    path('address/update/<int:pk>/', UserAddressUpdateView.as_view(), name='address_update'),
    path('address/delete/<int:pk>/', UserAddressDeleteView.as_view(), name='address_delete')


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/frontend/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% for cart in carts %}
{% if cart.carts.all %}
<div class="card">
    <div class="row">
        <div class="col-md-12 cart">
            <div class="title">
                <div class="row">
                    <div class="col"><h3 style="color: rgba(11, 122, 114, 1)">CART DETAILS</h3></div>
                </div>
            </div>
            <div class="row">
                <div class="row main align-items-center">
                    <div class="col-2">
                        <h5 style="color: rgba(11, 122, 114, 1)"></h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1)">Food Item</h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1)">Price</h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1)">Quantity</h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1)">Subtotal</h5>
                    </div>
                    <div class="col">
                        <h5 style="color: rgba(11, 122, 114, 1)"></h5>
                    </div>
                </div>
            </div>
            {% for item in cart.carts.all %}
            <div class="row border-top">
                <div class="row main align-items-center">
                    <div class="col-2">
                        <img class="img-fluid" src="{{ item.item.image.url }}" alt="Food Image"
                             style="width: 100px; height: 100px"/>
                    </div>
                    <div class="col">
                        <p class="mb-1" style="font-size: 20px;">{{ item.item.name }}</p>
                    </div>
                    <div class="col">
                        <div class="row"><b>₹ {{ item.item.price }}</b></div>
                    </div>
                    <div class="col">
                        <div class="input-group mb-3" style="max-width:85px">
                            <div>
                                <i class="fa-solid fa-minus fa-lg text-secondary" id="decreaseQuantity"
                                   onclick="location.href='{% url 'foodmania_website:decrease_quantity' item.id %}'">
                                </i>
                                &nbsp;
                                <b id="quantity">{{ item.quantity }}</b>
                                &nbsp;
                                <i class="fa fa-plus fa-lg" id="increaseQuantity" style="color: rgba(11, 122, 114, 1)"
                                   onclick="location.href='{% url 'foodmania_website:increase_quantity' item.id %}'">
                                </i>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        ₹ {{ item.sub_total }}
                    </div>
                    <div class="col">
                        <a href="{% url 'foodmania_website:remove_from_cart' item.id %}">
                            <i class="fa-solid fa-trash-can fa-lg text-danger"></i>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<br>
<div class="card mb-5">
    <div class="card-body p-4">
        <div class="float-end">
            <p class="mb-0 me-5 d-flex align-items-center">
                <span style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;">Cart Total:&nbsp;</span>
                <span class="lead fw-normal">₹ {{ cart.cart_total }}</span>
            </p>
        </div>
    </div>
</div>
<div style="display: flex; justify-content:flex-end">
    <div style="display: flex; justify-content:flex-end">
        <a class="btn btn-tertiary" href="{% url 'foodmania:food_list' %}"
           style="margin-right: 10px;color: rgba(11, 122, 114, 1)">Add Food Items</a>
        <a class="btn btn-primary" href="{% url 'foodmania_website:checkout' %}">Proceed to Checkout</a>
    </div>
</div>
<br>
{% else %}
<div class="card mb-5">
    <div class="card-body p-4">
        <div style="margin: auto">
            <p class="mb-0 me-5">
                <span>
                    <strong style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;margin: auto">
                        There are no items in your cart.
                    </strong>
                    <a class="btn btn-primary" href="{% url 'foodmania:food_list' %}"
                       style="margin-right: 10px;">Add Food Items</a>
                </span>
            </p>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endif %}
{% endfor %}

<link type="text/css" rel="stylesheet" href="{% static 'css/cart.css' %}"/>
<link type="text/css" rel="stylesheet" href="{% static 'css/select2.css' %}"/>
<script src="{% static 'js/modal_select2.js' %}"></script>
<script src="{% static 'js/toast.js' %}"></script>
{% endblock content %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

templates/frontend/cart/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
{% for cart in carts %}
{% if cart.carts.all %}
<form method="POST" action="{% url 'foodmania_website:payment' %}">
    <div class="card">
        <div class="row">
            <div class="col-md-12 cart">
                <div class="title">
                    <div class="row">
                        <div class="col">
                            <h3 style="color: rgba(11, 122, 114, 1);">CHOOSE DELIVERY ADDRESS</h3>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="row main align-items-center">
                        <div class="col">
                            {% csrf_token %}
                            {% if form.errors %}
                            {% for key, error in form.errors.items %}
                            {{ error }}
                            {% endfor %}
                            {% endif %}
                            {% render_field form.delivery_address %}
                        </div>
                        <div class="col">
                            <a class="btn btn-primary" href="{% url 'user:address_create' %}">Create new address</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="row">
            <div class="col-md-12 cart">
                <div class="title">
                    <div class="row">
                        <div class="col"><h3 style="color: rgba(11, 122, 114, 1)">ORDER DETAILS</h3></div>
                    </div>
                </div>
                <div class="row">
                    <div class="row main align-items-center">
                        <div class="col-2">
                            <h5 style="color: rgba(11, 122, 114, 1)"></h5>
                        </div>
                        <div class="col">
                            <h5 style="color: rgba(11, 122, 114, 1)">Food Item</h5>
                        </div>
                        <div class="col">
                            <h5 style="color: rgba(11, 122, 114, 1)">Price</h5>
                        </div>
                        <div class="col">
                            <h5 style="color: rgba(11, 122, 114, 1)">Quantity</h5>
                        </div>
                        <div class="col">
                            <h5 style="color: rgba(11, 122, 114, 1)">Subtotal</h5>
                        </div>
                    </div>
                </div>
                {% for item in cart.carts.all %}
                <div class="row border-top">
                    <div class="row main align-items-center">
                        <div class="col-2">
                            <img class="img-fluid" src="{{ item.item.image.url }}" alt="Food Image"
                                 style="width: 100px; height: 100px"/>
                        </div>
                        <div class="col">
                            <p class="mb-1" style="font-size: 20px;">{{ item.item.name }}</p>
                        </div>
                        <div class="col">
                            <div class="row"><b>₹ {{ item.item.price }}</b></div>
                        </div>
                        <div class="col">
                            {{ item.quantity }}
                        </div>
                        <div class="col">
                            ₹ {{ item.sub_total }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="row">
            <div class="col-md-12 cart">
                <div class="title">
                    <div class="row">
                        <div class="col">
                            <h3 style="color: rgba(11, 122, 114, 1);">ADD INSTRUCTIONS: (OPTIONAL)</h3>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="row main align-items-center">
                        <div class="col">
                        <textarea name="instructions" rows="3" placeholder="Enter Instructions"
                                  style="min-width: 100%">
                        </textarea>
                        </div>
                    </div>
                </div>
                <br>
            </div>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="row">
            <div class="col-md-12 cart">
                <div class="title">
                    <div class="row">
                        <div class="col">
                            <h3 style="color: rgba(11, 122, 114, 1);">ORDER SUMMARY</h3>
                        </div>
                    </div>
                </div>
                {% for cart in carts %}
                <div class="row">
                    <div class="row main align-items-center">
                        <div class="col">
                            <p class="mb-0 me-5 d-flex align-items-center">
                                <span style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;">
                                    Cart Total:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                </span>
                                <span class="lead fw-bold">₹ {{ cart.cart_total }}</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="row main align-items-center">
                        <div class="col">
                            <p class="mb-0 me-5 d-flex align-items-center">
                                <span style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;">
                                    Tax:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                </span>
                                <span class="lead fw-bold">₹ {{ cart.total_tax }}</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="row main align-items-center">
                        <div class="col">
                            <p class="mb-0 me-5 d-flex align-items-center">
                                <span style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;">
                                    Delivery Charges:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                </span>
                                {% if cart.delivery_charges == 0 %}
                                <span class="lead fw-bold" style="color: rgba(11, 122, 114, 1)">Free</span>
                                {% else %}
                                <span class="lead fw-bold">₹ {{ cart.delivery_charges }}</span>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="row main align-items-center">
                        <div class="col">
                            <p class="mb-0 me-5 d-flex align-items-center">
                                <span style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;">
                                    Total Amount:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                </span>
                                <span class="lead fw-bold">₹ {{ cart.order_total }}</span>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>
    <div style="display: flex; justify-content:flex-end">
        <div style="display: flex; justify-content:flex-end">
            <a class="btn btn-tertiary" href="{% url 'foodmania:food_list' %}"
               style="margin-right: 10px;color: rgba(11, 122, 114, 1)">Add Food Items</a>
            <button type="submit" class="btn btn-primary">Proceed to Payment</button>
        </div>
    </div>
    <br>
</form>
{% else %}
<div class="card mb-5">
    <div class="card-body p-4">
        <div style="margin: auto">
            <p class="mb-0 me-5">
                <span>
                    <strong style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;margin: auto">
                        There are no items in your cart.
                    </strong>
                    <a class="btn btn-primary" href="{% url 'foodmania:food_list' %}"
                       style="margin-right: 10px;">Add Food Items</a>
                </span>
            </p>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endif %}
{% endfor %}

<link type="text/css" rel="stylesheet" href="{% static 'css/cart.css' %}"/>
<link type="text/css" rel="stylesheet" href="{% static 'css/select2.css' %}"/>
<script src="{% static 'js/select2.js' %}"></script>
{% endblock content %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}