foodmania/urls.py
from django.urls import path
from foodmania.views import CategoryCreateView, CategoryListView, CategoryUpdateView, \
    CategoryDeleteView, FoodCreateView, FoodListView, FoodUpdateView, FoodDeleteView

app_name = 'foodmania'

urlpatterns = [


    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('food/create/', FoodCreateView.as_view(), name='food_create'),
    path('food/list/', FoodListView.as_view(), name='food_list'),
    path('food/update/<str:pk>/', FoodUpdateView.as_view(), name='food_update'),
    path('food/delete/<str:pk>/', FoodDeleteView.as_view(), name='food_delete')


]

foodmania_website/urls.py
from django.urls import path
from foodmania_website.views import HomePageView, OrderListView, OrderDetailView, \
    CheckoutView, AddToCartView, CartView, IncreaseItemQuantityView, DecreaseItemQuantityView, \
    RemoveItemFromCartView, AdminDashboardView, order_payment, callback, OrderDeliveredStatusView, \
    OrderRefundedStatusView, NewsLetterView

app_name = 'foodmania_website'

urlpatterns = [


    path('', HomePageView.as_view(), name='website'),
    path('dashboard/', AdminDashboardView.as_view(), name='dashboard'),

    path('add-to-cart/<int:pk>/', AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('increase-quantity/<int:pk>/', IncreaseItemQuantityView.as_view(), name='increase_quantity'),
    path('decrease-quantity/<int:pk>/', DecreaseItemQuantityView.as_view(), name='decrease_quantity'),
    path('remove-from-cart/<int:pk>/', RemoveItemFromCartView.as_view(), name='remove_from_cart'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/', order_payment, name='payment'),
    path('callback/', callback, name='callback'),
    path('order/list/', OrderListView.as_view(), name='order_list'),
    path('order/status/delivered/<int:pk>/', OrderDeliveredStatusView.as_view(), name='delivered_status'),
    path('order/status/refunded/<int:pk>/', OrderRefundedStatusView.as_view(), name='refunded_status'),
    path('order/detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('newsletter/', NewsLetterView.as_view(), name='newsletter')


]

rms/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path, include

urlpatterns = [


    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('foodmania.urls')),
    path('', include('user.urls')),
    path('', include('foodmania_website.urls')),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

user/urls.py
"""This file contains site deployment data such as server names and ports."""

from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView, \
    PasswordResetConfirmView, PasswordChangeView
from django.conf.urls.static import static
from user.views import SignupView, ProfileView, UserDeleteView, UserListView,\
    UserAddressCreateView, UserAddressListView, UserAddressUpdateView, UserAddressDeleteView
from user.forms import LoginForm
from rms import settings

app_name = 'user'

urlpatterns = [


    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name="registration/login.html",
                                     form_class=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/change/', PasswordChangeView.as_view(), name='password_change'),
    # path('password/change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('user/list/', UserListView.as_view(), name='user_list'),

    path('address/create/', UserAddressCreateView.as_view(), name='address_create'),
    path('address/list/', UserAddressListView.as_view(), name='address_list'),
    path('address/update/<int:pk>/', UserAddressUpdateView.as_view(), name='address_update'),
    path('address/delete/<int:pk>/', UserAddressDeleteView.as_view(), name='address_delete')


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0,
          minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Foodmania</title>
    <link rel="icon" type="image/x-icon" href="/media/foodmania.png">

    <!--bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet" crossorigin="anonymous"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--font awesome icons-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js"></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <link href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css" rel="stylesheet">
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <!--for bootstrap select2-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet">

    <!--Chart js-->
    <script crossorigin="anonymous"
            integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw="
            src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css"
          integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" rel="stylesheet"/>

    <!--Sweet Alert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!--Datatable-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css"
          rel="stylesheet">
    <link href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>

    <!--for custom css files-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/pagination.css' %}"/>
</head>
<body style="background: rgba(11, 122, 114, 0.2)">
<header>
    {% include 'navbar.html' %}
</header>
<main class="pt-5 mx-lg-5">
    <div class="container-fluid mt-5">
        {% block content %}
        {% endblock content %}
    </div>
</main>
<footer>
    {% block footer %}
    {% endblock footer %}
</footer>
</body>
</html>

templates/footer.html
{% load static %}
<!-- Footer -->
{% if user.is_superuser or user.is_staff %}
<footer class="footer" style="margin-bottom: 0px">
    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span style="color: #01514b">Foodmania</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <strong style="color: #01514b">Pakshal Shah</strong>
        </div>
    </div>
</footer>
{% else %}
<footer id="footer" class="footer" style="background: rgba(108, 117, 125, 0.6)">

    <div class="container">
        <div class="row gy-3">
            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="fa-solid fa-location-dot fa-lg" style="color: #01514b;"></i>&nbsp;
                <div>
                    <h4>Location</h4>
                    <p>
                        605, 6th floor, B-Square-1,<br>
                        Iscon-Ambali Road, Ahmedabad - 380058<br>
                    </p>
                </div>

            </div>

            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="fa-solid fa-phone fa-lg" style="color: #01514b;"></i>&nbsp;
                <div>
                    <h4>Reservations</h4>
                    <p>
                        <strong style="color: #01514b">Phone:</strong> +91 9876543210<br>
                        <strong style="color: #01514b">Email:</strong> foodmania@example.com<br>
                    </p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="fa-solid fa-clock fa-lg" style="color: #01514b;"></i>&nbsp;
                <div>
                    <h4>Open Hours</h4>
                    <p>
                        <strong style="color: #01514b">All Days: </strong>10AM - 2AM<br>
                    </p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 footer-links d-flex">
                <i class="fa-solid fa-arrow-right fa-lg" style="color: #01514b;"></i>&nbsp;
                <div>
                    <h4>Follow Us</h4>
                    <div class="social-links d-flex">
                        <a href="#" class="twitter"><i class="fa-brands fa-twitter"></i></a>
                        <a href="#" class="facebook"><i class="fa-brands fa-facebook-f"></i></a>
                        <a href="#" class="instagram"><i class="fa-brands fa-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="fa-brands fa-linkedin"></i></a>
                    </div>
                    <br>
                    <h4><i class="fa-solid fa-calendar-days" style="color: #01514b;"></i> Newsletter</h4>
                    <p>Enter email id for subscribing us to get all the latest updates.</p>
                    <div>
                        <form method="POST">
                            <div class="input-group mb-3 col-md-12">
                                <input type="email" class="form-control" aria-describedby="email-icon">
                                <span class="input-group-text" id="newsletter-send-icon">
                                    <i class="fa-solid fa-paper-plane" style="color: #0b7a72;"
                                       onclick="window.location.href='{% url 'foodmania_website:website' %}'"></i>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span style="color: #01514b">Foodmania</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <strong style="color: #01514b">Pakshal Shah</strong>
        </div>
    </div>

</footer>
{% endif %}
<!-- End Footer -->

<link type="text/css" rel="stylesheet" href="{% static 'css/footer.css' %}"/>

templates/navbar.html
{% load static %}
<!--Navbar-->
<nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background: rgba(108, 117, 125, 0.6)">
    <div class="container-fluid">
        {% if user.is_superuser or user.is_staff %}
        <a class="navbar-brand" href="{% url 'foodmania_website:dashboard' %}"
           style="color: rgba(11, 122, 114, 1)"><b>ADMIN MANAGEMENT</b></a>
        {% else %}
        <a class="navbar-brand" href="{% url 'foodmania_website:website' %}"
           style="color: rgba(11, 122, 114, 1)"><b>FOODMANIA</b></a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_superuser or user.is_staff %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'foodmania_website:order_list' %}"
                       style="color: rgba(11, 122, 114, 1);font-size: 18px;">Orders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:user_list' %}"
                       style="color: rgba(11, 122, 114, 1);font-size: 18px;">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'foodmania:category_list' %}"
                       style="color: rgba(11, 122, 114, 1);font-size: 18px;">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'foodmania:food_list' %}"
                       style="color: rgba(11, 122, 114, 1);font-size: 18px;">Foods</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'foodmania:food_list' %}"
                       style="color: rgba(11, 122, 114, 1);font-size: 18px;">Menu</a>
                </li>
            </ul>
            {% endif %}
            <ul class="navbar-nav d-flex flex-row ms-auto me-3">
                {% if user.is_superuser or user.is_staff %}
                {% else %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <button class="btn btn-tertiary position-relative"
                            data-bs-toggle="tooltip" data-bs-placement="bottom"
                            title="Cart Total: {{ request.user.mycart.last.set_total }}"
                            style="margin-top: 8px;margin-right: 15px;background: rgba(108, 117, 125, 0.6)"
                            onclick="location.href='{% url 'foodmania_website:cart' %}'">
                    <i class="fa-solid fa-cart-shopping fa-2xl" style="color: #01514b;"></i>
                    <span class="position-absolute top-0 start-100 translate-middle badge
                    rounded-pill bg-primary" id="cartItemQuantity">
                        {{ request.user.mycart.last.total_items }}
                    </span>
                    </button>
                </li>
                {% else %}
                <li class="nav-item">
                    <button class="btn btn-primary" onclick="location.href='{% url 'user:login' %}'">
                        Login/Register
                    </button>
                </li>
                {% endif %}
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item me-3 me-lg-0 dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.image.url }}" class="rounded-circle" height="40" width="50"
                             loading="lazy"/>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown1">
                        <li><p class="dropdown-item">Hello, <b>{{ user.username }}</b></p></li>
                        <li><a class="dropdown-item" href="{% url 'user:profile' user.id %}">
                            <i class="fa-solid fa-user"></i> My Profile</a>
                        </li>
                        {% if user.is_superuser or user.is_staff %}
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">
                            <i class="fa-solid fa-globe"></i> Admin Site</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'foodmania_website:website' %}">
                            <i class="fa-solid fa-globe"></i> My Website</a>
                        </li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'user:address_list' %}">
                            <i class="fa-solid fa-address-card"></i> My Address
                        </a></li>
                        <li>
                            <a class="dropdown-item"
                               href="{% url 'foodmania_website:order_list' %}">
                                <i class="fa-solid fa-address-card"></i> My Orders
                            </a>
                        </li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'user:logout' %}">
                                <i class="fa-solid fa-users"></i> Logout
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

<link type="text/css" rel="stylesheet" href="{% static 'css/navbar.css' %}"/>

templates/pagination.html
{% load static %}
<!--Pagination-->
<div id="bottom_left_link" style="margin-top: 25px">
    <b style="color: rgba(11, 122, 114, 1)">Page
        <b style="color: #01514b">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</b>
    </b>
</div>
<div></div>
<div class="justify-content-end" id="bottom_link" aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link btn btn-secondary"
                                 href="?&page=1">
            <b class="text-dark">&laquo;</b></a></li>
        <li class="page-item"><a class="page-link btn btn-secondary"
                                 href="?&page={{ page_obj.previous_page_number }}">
            <b class="text-dark">Previous</b></a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link btn btn-outline-secondary"
                                 href="?&page={{ page_obj.next_page_number }}">
            <b class="text-dark">Next</b></a></li>
        <li class="page-item"><a class="page-link btn btn-secondary"
                                 href="?&page={{ page_obj.paginator.num_pages }}">
            <b class="text-dark">&raquo;</b></a></li>
        {% endif %}
    </ul>
</div>
<!--End Pagination-->

templates/test_cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<script>
function getResponseForFoodCreate(){
    getToasterMessage("success", "Food Created Successfully");
    setTimeout(function() {
    $("#createFood").submit();
    }, 1500);
}

function getResponseForFoodDelete(){
    getToasterMessage("success", "Food Deleted Successfully");
    setTimeout(function() {
    $("#deleteFood").submit();
    }, 1500);
}



</script>

<!--Food List-->
<div class="row">
    {% if user.is_superuser or user.is_staff %}
    <div class="col-6">
        <!--Search-->
        <form class="d-flex input-group w-auto"
              action="{% url 'foodmania:food_list' %}">
            <input
                    type="search"
                    name="search"
                    class="form-control rounded"
                    id="search"
                    placeholder="Search for Pizza, Sandwich, Starter..."
            />
            <button type="submit" class="btn btn-secondary">
                <i class="fa fa-search fa-lg"></i> Search
            </button>
        </form>
    </div>
    <div class="col-6" align="center">
        <!--Filter-->
        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">
            Filter<i class="fa fa-filter fa-lg"></i>
        </button>
        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
            Sort By <i class="fa fa-sort fa-lg"></i>
        </button>
        <button type="reset" class="btn btn-tertiary"
                onclick="location.href='{% url 'foodmania:food_list' %}'">Clear all
        </button>
        <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal"
                data-bs-target="#exampleModal"><i class="fa fa-plus fa-lg"></i> Add Food
        </button>
        <div class="dropdown">
            <form action="{% url 'foodmania:food_list' %}" method="GET" onchange="this.form.submit()">
                <ul class="dropdown-menu">
                    <li>
                        <button class="dropdown-item" name="popularity">Popularity</button>
                    </li>
                    <li>
                        <button class="dropdown-item" name="price_low_to_high">Price low to high</button>
                    </li>
                    <li>
                        <button class="dropdown-item" name="price_high_to_low">Price high to low</button>
                    </li>
                </ul>
            </form>
        </div>
    </div>
    {% else %}
    <div class="col-8">
        <!--Search-->
        <form class="d-flex input-group w-auto"
              action="{% url 'foodmania:food_list' %}">
            <input
                    type="search"
                    name="search"
                    class="form-control rounded"
                    placeholder="Search for Pizza, Sandwich, Starter..."
            />
            <button type="submit" class="btn btn-secondary">
                <i class="fa fa-search fa-lg"></i> Search
            </button>
        </form>
    </div>
    <div class="col-4" align="center">
        <!--Filter-->
        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">
            Filter<i class="fa fa-filter fa-lg"></i>
        </button>
        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
            Sort By <i class="fa fa-sort fa-lg"></i>
        </button>
        <button type="reset" class="btn btn-tertiary"
                onclick="location.href='{% url 'foodmania:food_list' %}'">Clear all
        </button>
        <div class="dropdown">
            <form action="{% url 'foodmania:food_list' %}" method="GET" onchange="this.form.submit()">
                <ul class="dropdown-menu">
                    <li>
                        <button class="dropdown-item" name="popularity">Popularity</button>
                    </li>
                    <li>
                        <button class="dropdown-item" name="price_low_to_high">Price low to high</button>
                    </li>
                    <li>
                        <button class="dropdown-item" name="price_high_to_low">Price high to low</button>
                    </li>
                </ul>
            </form>
        </div>
    </div>
    {% endif %}
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" style="width: 250px;"
         id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Advanced Filters</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body" align="left">
            <form method="GET">
                {{ filter.form.as_p }}
                <button type="submit" class="btn btn-primary w-100">Apply Filter</button>
            </form>
        </div>
    </div>
</div>
<br>
{% if items %}
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for item in items %}
    <div class="col">
        <div class="card h-100" style="background: rgba(223, 236, 248, 1)">
            <img src="{{ item.image.url }}" class="card-img-top" alt="Food Image"
                 style="max-width:100%;min-width:100%;width:450px;height:150px;">
            <div class="card-body">
                <h5 class="card-title">{{ item.name }}</h5>
                <p class="card-text">{{ item.description|truncatechars:35 }}</p>
                <b class="card-text">₹ {{ item.price }}</b>
            </div>
            <div class="card-footer">
                {% if user.is_superuser or user.is_staff %}
                <div class="d-flex">
                    <a class="btn btn-outline-primary w-100"
                       href="{% url 'foodmania:food_update' item.pk %}"><i class="fa fa-edit fa-lg"></i> Edit
                    </a>
                    <button class="btn btn-outline-danger w-100" data-bs-toggle="modal"
                            data-bs-target="#DeleteModal{{ item.id }}"><i class="fa fa-trash-can fa-lg"></i> Delete
                    </button>
                </div>
                {% else %}
                {% if item.status == 'Enabled' %}
                <form action="{% url 'foodmania_website:add_to_cart' item.id %}" method="POST"
                      class="add-to-cart-form" id="addToCart">
                    {% csrf_token %}
                    {{ add_to_cart.as_p }}
                    <button type="submit" class="btn btn-primary w-100">Add To Cart</button>
                </form>
                {% else %}
                <strong>This item is out of stock.</strong>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <!-- Food Delete Modal -->
    <div class="modal fade" id="DeleteModal{{ item.id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5">Delete Food</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'foodmania:food_delete' item.id %}" method="POST"
                          id="deleteFood">
                        {% csrf_token %}
                        Are you sure you want to delete <b>{{ item.name }}</b>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary"
                                    data-bs-dismiss="modal">Cancel
                            </button>
                            <button type="button" class="btn btn-primary"
                                    onclick="getResponseForFoodDelete()">Delete
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% include 'pagination.html' %}
</div>

{% else %}
<div class="card mb-5">
    <div class="card-body p-4">
        <div style="margin: auto">
            <p class="mb-0 me-5">
                <span>
                    <strong style="color: rgba(11, 122, 114, 1);font-size: 20px;font-weight: bold;margin: auto">
                        No results found.
                    </strong>
                </span>
            </p>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endif %}
<!-- Food Create Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create Food</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'foodmania:food_create' %}" enctype="multipart/form-data"
                      method="POST" id="createFood">
                    {% csrf_token %}
                    {% if form.errors %}
                    {% for key, error in form.errors.items %}
                    {{ error }}
                    {% endfor %}
                    {% endif %}
                    {{ form.as_p }}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" onclick="getResponseForFoodCreate()">
                            Create
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!--End Food List-->

<script src="{% static 'js/cart/add_to_cart.js' %}"></script>
<script src="{% static 'js/toast.js' %}"></script>
<script src="{% static 'js/modal_select2.js' %}"></script>
<link type="text/css" rel="stylesheet" href="{% static 'css/select2.css' %}"/>
{% endblock content %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}